"""Python support tools for Tickline analysis and automation."""

from .analysis_report import (
    ANALYSIS_REPORT_SCHEMA_VERSION,
    REVIEW_DISPOSITIONS,
    AnalysisReportError,
    FindingReview,
    InvestigationAnalysisReport,
    analysis_report_document,
    build_analysis_report,
    render_analysis_report_json,
    write_analysis_report_json,
)
from .analytics import (
    CommandTypeStatistics,
    InvestigationStatistics,
    OutcomeStatistics,
    RejectionCodeStatistics,
    SessionStatistics,
    TickStatistics,
    analyze_investigation,
)
from .baseline import (
    InvestigationBaseline,
    InvestigationBaselineError,
    MetricBaseline,
    OutlierAnalysis,
    OutlierFinding,
    OutlierPolicy,
    build_investigation_baseline,
    evaluate_investigation_outliers,
)
from .investigation_bundle import (
    SUPPORTED_SCHEMA_VERSION,
    InvestigationBundle,
    InvestigationBundleValidationError,
    InvestigationEvidenceRecord,
    InvestigationSession,
    ReplaySummary,
    load_investigation_bundle,
    parse_investigation_bundle_json,
)

__all__ = [
    "ANALYSIS_REPORT_SCHEMA_VERSION",
    "REVIEW_DISPOSITIONS",
    "SUPPORTED_SCHEMA_VERSION",
    "AnalysisReportError",
    "CommandTypeStatistics",
    "FindingReview",
    "InvestigationAnalysisReport",
    "InvestigationBaseline",
    "InvestigationBaselineError",
    "InvestigationBundle",
    "InvestigationBundleValidationError",
    "InvestigationEvidenceRecord",
    "InvestigationSession",
    "InvestigationStatistics",
    "MetricBaseline",
    "OutcomeStatistics",
    "OutlierAnalysis",
    "OutlierFinding",
    "OutlierPolicy",
    "RejectionCodeStatistics",
    "ReplaySummary",
    "SessionStatistics",
    "TickStatistics",
    "__version__",
    "analysis_report_document",
    "analyze_investigation",
    "build_analysis_report",
    "build_investigation_baseline",
    "evaluate_investigation_outliers",
    "load_investigation_bundle",
    "parse_investigation_bundle_json",
    "render_analysis_report_json",
    "write_analysis_report_json",
]

__version__ = "1.0.0"
